import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>Logo</div>
          <ul>
            <li>Home</li>
            <li>Product</li>
            <li>Pricing</li>
            <li>About Us</li>
          </ul>
        </nav>
        {children}
        <div>This is footer</div>
      </body>
    </html>
  );
}
